### ISSUE TITLE
Topic lock replaces & with &amp;

### ISSUE THREAD

**Issue by nicatronTg** [NyxStudios/cardinal#10]
The title lock appears to be converting & to ```&amp;``` when changing topics back. This means that the topic replacement is not 1:1 when this character is used.

**Comment by Olink** [comment]
Slack api is used to set titles, we may need to urlencode the title text

**Comment by nicatronTg** [comment]
Fixed somewhere between 3a08a5bb8cb73fb356a8f18fbca0191090fbf3a8 and 7493336bf7552f3cc7f9e53282cac0e48939fbbe.
