### ISSUE TITLE
Sometimes, Camo links are generated incorrectly

### ISSUE THREAD

**Issue by nicatronTg** [NyxStudios/cardinal#11]
Not sure what causes this, but sometimes Camo links are generated and 404:

* https://ancient-meadow-2257.herokuapp.com/e21d3cbe8c024e73b5f411a2708cff160f0970c2?url=http%3A%2F%2Fdanbooru.donmai.us%2Fdata%2Fbed59747a81236db30048ae1b7b7b3ff.jpg

**Comment by Olink** [comment]
Go to heroku box and get logs

**Comment by nicatronTg** [comment]
Got it, will watch for more broken links.

**Comment by Olink** [comment]
Images exceeded config max size.

**Comment by nicatronTg** [comment]
Oh, that was this problem? Nice job finding it! :clap:
